### ISSUE TITLE
Getting org.flywaydb.core.api.FlywayException when I try to run Docker

### ISSUE THREAD

**Issue by jpteruel095** [DP-3T/dp3t-sdk-backend#50]
I feel like I've done everything, but I don't understand this last thing. I could run the jar using the java command provided at the README.md, but when I try using docker, I get this Flyway exception. "Found more than one migration with version 0.1"

What else am I supposed to do? I'm not used to developing on Java, let alone, a Java server (and manual builds at that), so I don't really understand the problems here. It seems to be a postgreSQL problem, but yeh I'm not sure what else to do as I can't find any solutions in this repository or somewhere in the internet.

```
2020-04-27 02:20:18,704 WARN [org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext] - <Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flywayInitializer' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Invocation of init method failed; nested exception is org.flywaydb.core.api.FlywayException: Found more than one migration with version 0.1
Offenders:
-> /home/ws/file:/home/ws/bin/dpppt-backend-sdk-ws.jar!/BOOT-INF/lib/dpppt-backend-sdk-data-1.0.0-SNAPSHOT.jar!/db/migration/pgsql/V0_1__init.sql (SQL)
-> /home/ws/file:/home/ws/bin/dpppt-backend-sdk-ws.jar!/BOOT-INF/lib/dpppt-backend-sdk-data-1.0.0-SNAPSHOT.jar!/db/migration/pgsql_cluster/V0_1__init.sql (SQL)>
2020-04-27 02:20:18,706 INFO [com.zaxxer.hikari.HikariDataSource] - <HikariPool-1 - Shutdown initiated...>
2020-04-27 02:20:18,721 INFO [com.zaxxer.hikari.HikariDataSource] - <HikariPool-1 - Shutdown completed.>
2020-04-27 02:20:18,727 INFO [org.apache.catalina.core.StandardService] - <Stopping service [Tomcat]>
2020-04-27 02:20:18,761 INFO [org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener] - <

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.>
2020-04-27 02:20:18,768 ERROR [org.springframework.boot.SpringApplication] - <Application run failed>
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flywayInitializer' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Invocation of init method failed; nested exception is org.flywaydb.core.api.FlywayException: Found more than one migration with version 0.1
Offenders:
-> /home/ws/file:/home/ws/bin/dpppt-backend-sdk-ws.jar!/BOOT-INF/lib/dpppt-backend-sdk-data-1.0.0-SNAPSHOT.jar!/db/migration/pgsql/V0_1__init.sql (SQL)
-> /home/ws/file:/home/ws/bin/dpppt-backend-sdk-ws.jar!/BOOT-INF/lib/dpppt-backend-sdk-data-1.0.0-SNAPSHOT.jar!/db/migration/pgsql_cluster/V0_1__init.sql (SQL)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1796)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:595)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:310)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:882)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
        at org.dpppt.backend.sdk.ws.Application.main(Application.java:24)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
Caused by: org.flywaydb.core.api.FlywayException: Found more than one migration with version 0.1
Offenders:
-> /home/ws/file:/home/ws/bin/dpppt-backend-sdk-ws.jar!/BOOT-INF/lib/dpppt-backend-sdk-data-1.0.0-SNAPSHOT.jar!/db/migration/pgsql/V0_1__init.sql (SQL)
-> /home/ws/file:/home/ws/bin/dpppt-backend-sdk-ws.jar!/BOOT-INF/lib/dpppt-backend-sdk-data-1.0.0-SNAPSHOT.jar!/db/migration/pgsql_cluster/V0_1__init.sql (SQL)
        at org.flywaydb.core.internal.resolver.CompositeMigrationResolver.checkForIncompatibilities(CompositeMigrationResolver.java:144)
        at org.flywaydb.core.internal.resolver.CompositeMigrationResolver.doFindAvailableMigrations(CompositeMigrationResolver.java:109)
        at org.flywaydb.core.internal.resolver.CompositeMigrationResolver.resolveMigrations(CompositeMigrationResolver.java:92)
        at org.flywaydb.core.internal.resolver.CompositeMigrationResolver.resolveMigrations(CompositeMigrationResolver.java:45)
        at org.flywaydb.core.internal.info.MigrationInfoServiceImpl.refresh(MigrationInfoServiceImpl.java:130)
        at org.flywaydb.core.internal.command.DbValidate$2.call(DbValidate.java:138)
        at org.flywaydb.core.internal.command.DbValidate$2.call(DbValidate.java:126)
        at org.flywaydb.core.internal.jdbc.TransactionTemplate.execute(TransactionTemplate.java:74)
        at org.flywaydb.core.internal.command.DbValidate.validate(DbValidate.java:126)
        at org.flywaydb.core.Flyway.doValidate(Flyway.java:269)
        at org.flywaydb.core.Flyway.access$100(Flyway.java:79)
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:157)
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:149)
        at org.flywaydb.core.Flyway.execute(Flyway.java:511)
        at org.flywaydb.core.Flyway.migrate(Flyway.java:149)
        at org.springframework.boot.autoconfigure.flyway.FlywayMigrationInitializer.afterPropertiesSet(FlywayMigrationInitializer.java:65)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1855)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1792)
        ... 26 common frames omitted
```

**Comment by martinalig** [comment]
Hi
First, apologize, the README is not fully up-to-date. We will try to improve this during the next days.
Could you make sure, that you only have the "prod" profile active?

**Comment by jpteruel095** [comment]
> Hi
> First, apologize, the README is not fully up-to-date. We will try to improve this during the next days.
> Could you make sure, that you only have the "prod" profile active?

Hello! Thank you for the active reply. 
If I may ask, where can I change that? I encountered the application.properties file in some other issues here, and I'm not sure if it's the same file I'm going to change? Thank you.

**Comment by jpteruel095** [comment]
I'm trying to change the one in the application.properties file

```spring.profiles.active=prod```

But I get this in the log when I try to build it with mvn install 

```
2020-04-27 08:21:43,587 INFO [org.dpppt.backend.sdk.ws.controller.DPPPTControllerTest] - <The following profiles are active: dev,jwt>
```

**Comment by bachmann-ubique** [comment]
You are setting the property correctly. 
The log output you provided, is from a Test. Some Tests are peformed with the jwt profile.
But the jar you will get, will be without the jwt profile.
